services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8081"
    environment:
      WATCHPACK_POLLING: "true"
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules/
            - dist/
            - .git/
        - action: rebuild
          path: package.json
        - action: rebuild
          path: package-lock.json
